### ISSUE TITLE
.NET data directory RVA is 0

### ISSUE THREAD

**Issue by chenscottus** [Sato-Isolated/MindLated#48]
Hello,

 When I try to protect the application, here is the error:

Form1.cs:line 91
	Md = ModuleDefMD.Load(textBox1.Text);
System.BadImageFormatException
  HResult=0x8007000B
  Message=.NET data directory RVA is 0
  Source=dnlib
  StackTrace:
   at dnlib.DotNet.MD.MetadataFactory.Create(IPEImage peImage, CLRRuntimeReaderKind runtime, Boolean verify)
   at dnlib.DotNet.MD.MetadataFactory.Load(IPEImage peImage, CLRRuntimeReaderKind runtime)
   at dnlib.DotNet.MD.MetadataFactory.Load(String fileName, CLRRuntimeReaderKind runtime)
   at dnlib.DotNet.ModuleDefMD.Load(String fileName, ModuleCreationOptions options)
   at MindLated.Form1.Button1_Click(Object sender, EventArgs e) in D:\Workspace2023\Project2023\20230518\MindLated-master\Form1.cs:line 91
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Thanks!

-Scott

**Comment by Sato-Isolated** [comment]
Hi, is your application in .NET or native, because if it's native that why u can't load.

**Comment by chenscottus** [comment]
Right, a dll works but not the exe file in.Net7Thanks       Best Regards,- ScottOn May 22, 2023, at 6:43 PM, MindLated ***@***.***> wrote:﻿
Hi, is your application in .NET or native, because if it's native that why u can't load.

**Comment by Sato-Isolated** [comment]
yeah in .NET Core u can't obfuscate the "winformapp1".exe file u need to obfuscate the "winformapp1".dll
